steps:
- task: NodeTool@0
  inputs:
    versionSpec: 12.x

- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.7'
    architecture: 'x64'

- bash: |
    npm install
    npm run dist
  displayName: Build
