trigger:
- refs/heads/*
- refs/pull/*/merge

jobs:
- job: windows_build
  displayName: 'Build for Windows'
  pool:
    vmImage: 'VS2017-Win2016'
  strategy:
    matrix:
      x64:
        npm_config_arch: x64
      x86:
        npm_config_arch: ia32
  steps:
  - template: azure-pipelines-template.yml

- job: macos_build
  displayName: 'Build for macOS'
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      x64:
        npm_config_arch: x64
  steps:
  - template: azure-pipelines-template.yml

- job: linux_build
  displayName: 'Build for Linux'
  pool:
    vmImage: 'ubuntu-18.04'
  strategy:
    matrix:
      x64:
        npm_config_arch: x64
  steps:
  - script: |
      sudo apt update
      sudo apt install -y git cmake xvfb g++-7 libgtk-3-dev libnotify-dev webkit2gtk-4.0-dev
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 1000;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 1000;
    displayName: Install dependencies
  - template: azure-pipelines-template.yml
