version: 2

custom-steps:
  - &install-deps
    run:
      name: Install dependencies
      command: |
        apt-get update
        apt-get install -y software-properties-common
        add-apt-repository -y ppa:webkit-team/ppa
        add-apt-repository -y ppa:ubuntu-toolchain-r/test
        apt-get update
        apt-get install -y git cmake g++-6 xvfb libgtk-3-dev libnotify-dev webkit2gtk-4.0-dev
  - &install-node
    run:
      name: Install Node.js
      command: |
        curl -sL https://deb.nodesource.com/setup_8.x | bash -
        apt-get install -y nodejs

jobs:
  muban-linux-x64:
    docker:
      - image: ubuntu:16.04
        environment:
          - DISPLAY=:99.0
    steps:
      - *install-deps
      - *install-node
      - checkout
      - run: npm install
      - run: npm run dist

workflows:
  version: 2
  build:
    jobs:
      - muban-linux-x64
